name: Build Python Packages (Linux & Windows)

on:
  push:
    branches: [main]
    tags: ["v*"] 
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build the package
        run: python -m build

      - name: Upload build dist
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/
          retention-days: 1

  collect:
    name: Collect all wheels and source into final artifact
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create final-dist directory
        run: mkdir final-dist
        
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: final-dist

      - name: Upload unified dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-muppi-neurips
          path: final-dist/

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Build release
          tag_name: dist-${{ github.run_number }}
          files: final-dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up previous builds
        run: rm -rf final-dist && mkdir final-dist


