name: Mirror to GitLab

on: [push]
  
jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Mirror to GitLab
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.lis-lab.fr/dev/muppi_neurips"
        env:
          GITLAB_HOSTNAME: "https://gitlab.lis-lab.fr/"
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
